# Generated by Django 4.1 on 2022-11-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_season_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_tb',
            old_name='name',
            new_name='seasonname',
        ),
    ]
