# Generated by Django 4.1 on 2022-11-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_rename_name_season_tb_seasonname'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=20)),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.season_tb')),
            ],
        ),
    ]
