# Generated by Django 4.1 on 2022-11-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_seasoncountry_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_tb',
            old_name='seasonname',
            new_name='name',
        ),
    ]
