# Generated by Django 4.1 on 2022-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_seasoncountry_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minage', models.IntegerField()),
                ('maxage', models.IntegerField()),
                ('factor', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='seasoncountry_tb',
        ),
    ]
