# Generated by Django 4.1 on 2022-11-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hobby_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('filterstatus', models.CharField(default='pending', max_length=20)),
                ('reciverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='user.register_tb')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.register_tb')),
            ],
        ),
    ]
