# Generated by Django 4.1 on 2022-11-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.message_tb')),
                ('reciverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
