# Generated by Django 4.1 on 2022-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_agefactor_tb_delete_seasoncountry_tb'),
        ('user', '0010_custumeragefactor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custumeragefactor',
            new_name='custumeragefactor_tb',
        ),
    ]
