# Generated by Django 4.1 on 2022-12-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_agefactor_tb_delete_seasoncountry_tb'),
        ('user', '0011_rename_custumeragefactor_custumeragefactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='custumerseasoncountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasonfactor_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
